[window]
padding.x = 6
padding.y = 6

opacity = 0.1

[font]
normal.family = "UbuntuMono Nerd Font"
bold.family = "UbuntuMono Nerd Font"
italic.family = "UbuntuMono Nerd Font"
bold_italic.family = "UbuntuMono Nerd Font"

normal.style = 'Bold'
size = 10
