[window]
padding.x = 6
padding.y = 6

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

normal.style = 'Bold'
size = 12
