[connection]
id=infosis

[vpn]
gateway=vpn.infosis.com.ar
user-auth-type=password
user=joalvarez
machine-auth-type=psk
ipsec-enabled=true

[ip4]
method=auto
ignore-auto-routes=false
ignore-auto-dns=false
dhcp-send-hostname=true
never-default=false
